### ISSUE TITLE
Could you please offed the trained model?

### ISSUE THREAD

**Issue by Watebear** [fvmassoli/cross-resolution-face-recognition#13]
Hello, I am very interested in your work and thank you for shared the codes.
I would like to reimplement your work but i can't get the se-resnet-50 model. The link in that work can't reach.
Could you please share your model weights?
Thank you very much.

**Comment by fvmassoli** [comment]
I updated the link in the readme to download the original base model trained published by the VGG group.
Note that in the folder you will download there is the model checkpoint and the package MainModel.py. You need both to load the model since it is not native for pytorch but it has been converted from caffe.

Actually, the MainModel.py comes already with the repo when you clone it.
